name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-20.04
    steps:
      - name: List files in the repository
        run: |
          mkdir -p /opt/kata-materials
          cd /opt/kata-materials
          git clone --depth 1 https://github.com/irixjp/katacoda-scenarios.git .
          pip install virtualenv
          virtualenv ansible
          source /opt/kata-materials/ansible/bin/activate
          cd tools
          bash ./kata_setup.sh
          cd ~/
          ansible --version
          ls -alF
          pwd
          echo $HOME
          cat /etc/passwd
          sudo ls -alF /root
          sudo cp -r /root/inventory_file /root/.ansible.cfg /opt/kata-materials/materials /home/runner
          ls -alF
